laser_filter_node:
  ros__parameters:
    scan_filter_chain:
      - name: range_filter
        type: laser_filters/LaserScanRangeFilter
        params:
          use_message_range_limits: false
          lower_threshold: 0.15
          upper_threshold: 8.0
          lower_replacement_value: nan
          upper_replacement_value: nan
      - name: body_angle_filter
        type: laser_filters/LaserScanAngularBoundsFilterInPlace
        params:
          lower_angle: -2.88
          upper_angle: 2.88
      - name: footprint_filter
        type: laser_filters/LaserScanFootprintFilter
        params:
          inscribed_radius: 0.22
      - name: median_filter
        type: laser_filters/LaserScanMedianFilter
        params:
          window_size: 3
      - name: nan_remover
        type: laser_filters/LaserScanValidPointsFilter
        params:
          remove_nans: true
